version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: api_cyberpunk
      POSTGRES_PASSWORD: api_pswd
      POSTGRES_DB: cyberpunk
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
